namespace WooAsset
{
    [System.Serializable]
    public enum AssetType
    {
        None,
        Meta,
        CS,
        Directory,
        Texture,
        Shader,
        ShaderVariant,
        VideoClip,
        AudioClip,
        Scene,
        Material,
        Prefab,
        Font,
        Animation,
        AnimationClip,
        AnimatorController,
        SpriteAtlas,
        ScriptObject,
        Model,
        TextAsset,
        Raw,
        RawObject,
        RawCopyFile,
    }
}
